version: 1
# amqp config for connecting to amqp server
amqp:
  host: "localhost"
  port: 5672
  user: "mira_rabbit"
  password: "f8d6acfa7b8b"

# amqp url has higher priority than amqp config object
amqpUrl: ''

downloader: 'qbittorrent' # Currently, only support 'deluge' and 'qbittorrent
# download location support variable like ${home} ${cwd} ${project_root}
download_location: '${home}/Videos/albireo'

download_manager_id: 'Mikage'
deluge:
  json_rpc_url: 'http://localhost:8112/json'
  password: 'deluge'
qBittorrent:
  api_url: 'http://localhost:8091/api/v2'
  username: 'admin'
  password: 'Pc2hwfwIeWH1'

# used for composing the url for downloading output file from job executor, default is http://localhost:8000/output/
webserver:
  enableHttps: false
  host: "localhost"
  port: 8081

# will deprecate once Albireo is deprecated
albireoRPC: 'http://localhost:8080'

# how long to remove completed download job.
completed_job_retention: 30 # days

# S3 or Filesystem
storage_type: 'Filesystem'

# this will be passed into S3Client() as configuration
s3_config:
  endpoint: 'http://127.0.0.1:8333'
  # specify region since it is mandatory, but it will be ignored by seaweedfs
  region: 'us-east-1'
  # force path style for compatibility reasons
  forcePathStyle: true
  # dual stack endpoint is not supported by seaweed
  useDualstackEndpoint: false
  # checksum validation should be disabled, overwise `x-amz-checksum` will be injected directly into files
  responseChecksumValidation: 'WHEN_REQUIRED'
  requestChecksumCalculation: 'WHEN_REQUIRED'
  # credentials are mandatory and s3 authorization should be enabled with `s3.configure`
  credentials:
    accessKeyId: 'admin'
    secretAccessKey: 'admin'

# This bucket is used to share downloaded file with mira-video-manager.
s3_bucket:
  name: 'internal-download-files'
  expireInDays: 3 # Indicates the lifetime, in days, of the objects that are subject to the rule. The value must be a non-zero positive integer.